image: golang
prelude:
- apt-get update
- apt-get install -y make git
- git clone https://github.com/Luet-lab/extensions
- cd extensions && git checkout -b build v${PACKAGE_VERSION}
- mkdir /luet-extensions
- cd extensions && make build
package_dir: "/luet-extensions"
steps:
- cd extensions && DESTDIR=/luet-extensions make install

