{{ if eq .Values.name "luet-migrate-entropy" }}
image: "golang"
{{ else }}
requires:
- category: "system"
  name: "luet"
  version: ">=0"
{{end}}
env:
- BUNDLED_EXTENSIONS="{{.Values.extensions}}"
prelude:
{{ if eq .Values.name "luet-migrate-entropy" }}
- apt-get update && apt-get install -y make git
{{ else }}
- apk add make git
{{end}}
- git clone https://github.com/Luet-lab/extensions
{{- if not .Values.live }}
- |
   PACKAGE_VERSION=${PACKAGE_VERSION%\+*} && \
   cd extensions && git checkout -b build v${PACKAGE_VERSION}
{{- end }}
- mkdir /luet-extensions
- cd extensions && make build
package_dir: "/luet-extensions"
steps:
- cd extensions && DESTDIR=/luet-extensions make install

