requires:
- category: "system"
  name: "luet"
  version: ">=0"
env:
- BUNDLED_EXTENSIONS="{{.Values.extensions}}"
prelude:
- apk add make git
- git clone https://github.com/Luet-lab/extensions
{{- if not .Values.live }}
- |
   PACKAGE_VERSION=${PACKAGE_VERSION%\+*} && \
   cd extensions && git checkout -b build v${PACKAGE_VERSION}
{{- end }}
- mkdir /luet-extensions
- go get gopkg.in/yaml.v3
- cd extensions && make build
package_dir: "/luet-extensions"
steps:
- cd extensions && DESTDIR=/luet-extensions make install

