image: golang:alpine
prelude:
- apk update
- apk add git
- git clone https://github.com/mudler/luet

env:
- CGO_ENABLED=0
{{ if eq .Values.name "luet-arm" }}
- GOARCH=arm
{{end}}
steps:
- |
  PACKAGE_VERSION=${PACKAGE_VERSION%\+*} && \
  cd luet && git checkout "${PACKAGE_VERSION}" -b build && \
  go build -ldflags="-w -s -X github.com/mudler/luet/cmd.BuildTime=$(date -u '+%Y-%m-%d') -X github.com/mudler/luet/cmd.BuildCommit=$(git rev-parse HEAD)" && mv luet /usr/bin/luet
includes:
- /usr/bin/luet
