image: golang
environment:
- GOPATH=/go
prelude:
- apt-get update
- apt-get install git
- mkdir -p $GOPATH/src/github.com/GoogleContainerTools
- git clone https://github.com/GoogleContainerTools/container-diff $GOPATH/src/github.com/GoogleContainerTools/container-diff
steps:
- cd $GOPATH/src/github.com/GoogleContainerTools/container-diff && git checkout -b build v0.15.0 && go build && mv container-diff /usr/bin/container-diff
includes:
- /usr/bin/container-diff
