image: golang:alpine
prelude:
- apk add make git
- git clone https://github.com/mudler/entities
steps:
- cd entities && git checkout "${PACKAGE_VERSION}" && make build && mv entities /usr/bin/entities
- cp -rfv /usr/bin/entities /usr/bin/luet-entities
includes:
- /usr/bin/entities
- /usr/bin/luet-entities
