image: golang
prelude:
- apt-get update
- apt-get install -y make git
- git clone https://github.com/Luet-lab/extensions
- mkdir /luet-extensions
- go get gopkg.in/yaml.v3
- cd extensions && make build
package_dir: "/luet-extensions"
steps:
- cd extensions && DESTDIR=/luet-extensions make install

