image: golang:alpine
prelude:
- apk add git upx make
- git clone https://github.com/mudler/luet-makeiso
steps:
- |
  PACKAGE_VERSION=${PACKAGE_VERSION%\+*} && \
  cd luet-makeiso && git checkout "${PACKAGE_VERSION}" && make build-small && mv luet-makeiso /usr/bin/luet-makeiso
includes:
- /usr/bin/luet-makeiso
